language: node_js
node_js:
  - '10'
  - '8'

install:
  - yarn
  - yarn compile

script:
  - yarn lint && yarn test:travis && yarn report-coverage

cache:
  yarn: true
  directories:
    - node_modules
